### ISSUE TITLE
documentation on brake

### ISSUE THREAD

**Issue by Cncninja** [alextreseder/picoEDM#2]
I'm building the pico and don't understand how the brake is making drage it has a stepper connected is the stepper shorted to cause drag? or is it under driven vs the respooler.

**Comment by alextreseder** [comment]
Braking is accomplished with an integrated closed loop driver that is capable of a sort of pseudo-"torque mode" that works plenty well enough with not too much cogging. We basically use a stepper motor to emulate an adjustable rotary damper. Ideally, this means the motor driver tries to keep the velocity at 0 with some allowable torque limit. 

MKS s42d works for the torque effect but it is not possible to set the velocity to 0. That means you have to have it try to hold a position, so if your wire breaks, the motor will spin all the way back to position 0 which is a nuisance. This is a firmware problem but the firmware is not open source. 

CLN17 v2 from creapunk should be the fix for this. However, they are still in beta testing and a little hard to get your hands on. I recommend you use the MKSs42d for now, put a button on the power source so you can reset the device if the wire breaks. 

Cheers

**Comment by alextreseder** [comment]
Ill add this to the documentation when the new version goes fully live
